// swift-tools-version:5.9
//
// kiromi-ai-swift — public Swift Package for the KiromiAI memory store.
//
// Generated by scripts/bump-version.sh — do not edit the binaryTarget
// block by hand. To bump to a new kiromi-mem release, run:
//
//     bash scripts/bump-version.sh v0.X.Y --commit --tag --release
//
// The wrapper Swift sources under Sources/KiromiAI/ are regenerated
// from the kiromi-mem source tree on every release. Do not hand-edit;
// submit changes upstream to https://github.com/kiromi-ai/kiromi-mem.

import PackageDescription

let package = Package(
    name: "KiromiAI",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .library(name: "KiromiAI", targets: ["KiromiAI"]),
    ],
    targets: [
        .binaryTarget(
            name: "KiromiAIFFI",
            url: "https://github.com/kiromi-ai/kiromi-ai-swift/releases/download/v0.2.4/KiromiAIFFI.xcframework.zip",
            checksum: "241cdd164ee69d03dac3bd523ede28bfe615b95c9bfc143ed529dee15d83935f"
        ),
        .target(
            name: "SwiftBridgeGenerated",
            dependencies: ["KiromiAIFFI"],
            path: "Sources/SwiftBridgeGenerated"
        ),
        .target(
            name: "KiromiAI",
            dependencies: ["SwiftBridgeGenerated"],
            path: "Sources/KiromiAI",
            linkerSettings: [
                .linkedLibrary("c++"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
            ]
        ),
        .testTarget(
            name: "KiromiAITests",
            dependencies: ["KiromiAI"],
            path: "Tests/KiromiAITests"
        ),
    ]
)
