#!/usr/bin/env bash
# Bump kiromi-ai-swift to a new release version.
#
# What it does:
#   1. Downloads the matching KiromiAIFFI.xcframework.zip from the
#      kiromi-ai/kiromi-mem private GitHub release (using `gh` CLI auth).
#   2. Verifies its SwiftPM checksum.
#   3. Syncs Sources/KiromiAI/ and Sources/SwiftBridgeGenerated/ from a
#      local kiromi-mem clone (so the wrapper Swift code stays in sync
#      with the binary's C ABI).
#   4. Updates Package.swift to point at this repo's *public* release
#      URL with the new checksum.
#   5. Stages the changes — by default does NOT auto-commit so the
#      operator can review.
#
# Usage:
#   bash scripts/bump-version.sh v0.2.0 [--commit] [--tag] [--release]
#
# Flags:
#   --commit            git commit the staged changes
#   --tag               also create the matching git tag
#   --release           also create the GitHub release (uploads the zip)
#
# Required env / state:
#   - `gh` CLI authenticated against github.com with read access to
#     kiromi-ai/kiromi-mem and write access to kiromi-ai/kiromi-ai-swift.
#   - kiromi-mem cloned at $KIROMI_MEM_PATH (defaults to ../kiromi-mem
#     relative to this repo).

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "usage: $(basename "$0") <tag> [--commit] [--tag] [--release]" >&2
    exit 1
fi

TAG="$1"
shift
DO_COMMIT=0
DO_TAG=0
DO_RELEASE=0
for arg in "$@"; do
    case "$arg" in
        --commit) DO_COMMIT=1 ;;
        --tag) DO_TAG=1 ;;
        --release) DO_RELEASE=1 ;;
        *) echo "unknown flag: $arg" >&2; exit 1 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

KIROMI_MEM_PATH="${KIROMI_MEM_PATH:-$ROOT/../kiromi-mem}"
if [[ ! -d "$KIROMI_MEM_PATH/crates/kiromi-ai-swift/swift/Sources" ]]; then
    echo "error: kiromi-mem clone not found at $KIROMI_MEM_PATH" >&2
    echo "       set KIROMI_MEM_PATH to a local clone of kiromi-ai/kiromi-mem" >&2
    exit 1
fi

# The repo this script is bumping. Used to construct the binary URL.
THIS_REPO="kiromi-ai/kiromi-ai-swift"
RELEASE_URL="https://github.com/$THIS_REPO/releases/download/$TAG/KiromiAIFFI.xcframework.zip"

# 1. Download the xcframework from the kiromi-mem release.
WORK_DIR="$(mktemp -d)"
trap "rm -rf '$WORK_DIR'" EXIT
echo "=> downloading KiromiAIFFI.xcframework.zip from kiromi-ai/kiromi-mem@$TAG"
gh release download "$TAG" \
    -R kiromi-ai/kiromi-mem \
    -p 'KiromiAIFFI.xcframework.zip' \
    -p 'KiromiAIFFI.xcframework.zip.sha256' \
    --dir "$WORK_DIR"

# 2. Verify the checksum file the kiromi-mem CI emitted.
EXPECTED="$(awk '{print $1}' "$WORK_DIR/KiromiAIFFI.xcframework.zip.sha256")"
ACTUAL="$(shasum -a 256 "$WORK_DIR/KiromiAIFFI.xcframework.zip" | awk '{print $1}')"
if [[ "$EXPECTED" != "$ACTUAL" ]]; then
    echo "checksum mismatch:" >&2
    echo "  expected: $EXPECTED" >&2
    echo "  actual:   $ACTUAL" >&2
    exit 1
fi
echo "ok: $ACTUAL"
# SwiftPM's compute-checksum is sha256 of the zip — same as the file's
# .sha256. Confirmed from the kiromi-mem release-artifacts.yml workflow.
SWIFTPM_CHECKSUM="$ACTUAL"

# 3. Sync Swift sources from kiromi-mem.
echo "=> syncing Sources/KiromiAI/ and Sources/SwiftBridgeGenerated/ from kiromi-mem"
rsync -a --delete \
    "$KIROMI_MEM_PATH/crates/kiromi-ai-swift/swift/Sources/KiromiAI/" \
    "$ROOT/Sources/KiromiAI/"
rsync -a --delete \
    "$KIROMI_MEM_PATH/crates/kiromi-ai-swift/swift/Sources/SwiftBridgeGenerated/" \
    "$ROOT/Sources/SwiftBridgeGenerated/"

# Sync tests too — they're a useful regression suite.
if [[ -d "$KIROMI_MEM_PATH/crates/kiromi-ai-swift/swift/Tests/KiromiAITests" ]]; then
    rsync -a --delete \
        "$KIROMI_MEM_PATH/crates/kiromi-ai-swift/swift/Tests/KiromiAITests/" \
        "$ROOT/Tests/KiromiAITests/"
fi

# 4. Stage Frameworks/ — extract the zip so local `swift build` works
#    even before the URL form resolves over the wire.
echo "=> staging Frameworks/KiromiAIFFI.xcframework"
rm -rf "$ROOT/Frameworks/KiromiAIFFI.xcframework"
mkdir -p "$ROOT/Frameworks"
unzip -q "$WORK_DIR/KiromiAIFFI.xcframework.zip" -d "$ROOT/Frameworks/"
# Keep the zip too; we'll attach it to the GH release.
cp "$WORK_DIR/KiromiAIFFI.xcframework.zip" "$ROOT/Frameworks/"

# 5. Rewrite Package.swift to URL form with the new checksum.
echo "=> rewriting Package.swift (url form for $TAG)"
cat > "$ROOT/Package.swift" <<EOF
// swift-tools-version:5.9
//
// kiromi-ai-swift — public Swift Package for the KiromiAI memory store.
//
// Generated by scripts/bump-version.sh — do not edit the binaryTarget
// block by hand. To bump to a new kiromi-mem release, run:
//
//     bash scripts/bump-version.sh v0.X.Y --commit --tag --release
//
// The wrapper Swift sources under Sources/KiromiAI/ are regenerated
// from the kiromi-mem source tree on every release. Do not hand-edit;
// submit changes upstream to https://github.com/kiromi-ai/kiromi-mem.

import PackageDescription

let package = Package(
    name: "KiromiAI",
    platforms: [
        .macOS(.v13),
    ],
    products: [
        .library(name: "KiromiAI", targets: ["KiromiAI"]),
    ],
    targets: [
        .binaryTarget(
            name: "KiromiAIFFI",
            url: "$RELEASE_URL",
            checksum: "$SWIFTPM_CHECKSUM"
        ),
        .target(
            name: "SwiftBridgeGenerated",
            dependencies: ["KiromiAIFFI"],
            path: "Sources/SwiftBridgeGenerated"
        ),
        .target(
            name: "KiromiAI",
            dependencies: ["SwiftBridgeGenerated"],
            path: "Sources/KiromiAI",
            linkerSettings: [
                .linkedLibrary("c++"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
            ]
        ),
        .testTarget(
            name: "KiromiAITests",
            dependencies: ["KiromiAI"],
            path: "Tests/KiromiAITests"
        ),
    ]
)
EOF

# 6. Stage everything for review.
git add Package.swift Sources/ Tests/
echo
echo "Staged changes for $TAG."
git status --short

# 7. Optional: commit / tag / release.
if [[ $DO_COMMIT -eq 1 ]]; then
    git commit -m "release($TAG): sync sources + binaryTarget url+checksum from kiromi-mem"
fi
if [[ $DO_TAG -eq 1 ]]; then
    git tag -a "$TAG" -m "kiromi-ai-swift $TAG (kiromi-mem $TAG)"
fi
if [[ $DO_RELEASE -eq 1 ]]; then
    echo "=> creating GitHub release $TAG on $THIS_REPO"
    gh release create "$TAG" \
        -R "$THIS_REPO" \
        --title "kiromi-ai-swift $TAG" \
        --notes "Tracks [kiromi-ai/kiromi-mem $TAG](https://github.com/kiromi-ai/kiromi-mem/releases/tag/$TAG).

## SwiftPM
\`\`\`swift
.package(url: \"https://github.com/$THIS_REPO\", from: \"${TAG#v}\"),
\`\`\`

## Binary verification
\`\`\`
KiromiAIFFI.xcframework.zip
  sha256: $SWIFTPM_CHECKSUM
\`\`\`" \
        "$ROOT/Frameworks/KiromiAIFFI.xcframework.zip"
fi

echo
echo "Done. Next steps:"
[[ $DO_COMMIT -eq 0 ]] && echo "  - review staged diff, commit"
[[ $DO_TAG -eq 0 ]] && echo "  - git tag -a $TAG -m '...'"
[[ $DO_RELEASE -eq 0 ]] && echo "  - gh release create $TAG --title '...' --notes '...' Frameworks/KiromiAIFFI.xcframework.zip"
echo "  - git push && git push --tags"
